<a href="https://colab.research.google.com/github/chhinger/01_Python_Introduction/blob/main/AcdemicRisk.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
import pandas as pd
import csv

# **1. LOADING DATA**

In [4]:

data = pd.read_csv("/content/drive/MyDrive/Students_Data/ITCStudentData.csv", encoding='latin1')
data.head()

,ID,Gender,Age,EduLevel,Year,MediaTime,FamChallenge,Relationship,EngLevel,SleepTime,...,MediaEntertain,ClassMedia,ClassMessChat,ClassEntertain,ClassGames,ClassMovies,MindIntelligence,MindLearnMistake,MindSeekHelp,MindGroupWork
0,1,Male,21,Bachelor/Engineering,4,4.0,6.0,Single,Advanced,5  6,...,More than 3 hours,4,4,4,0,0,5,5,5,5
1,2,Male,21,Bachelor/Engineering,4,7.0,2.0,Single,Advanced,7  8,...,More than 3 hours,3,3,3,1,1,6,6,6,6
2,3,Male,21,Bachelor/Engineering,4,8.0,3.0,Single,Advanced,5  6,...,More than 3 hours,4,3,3,0,4,6,6,5,4
3,5,Male,22,Bachelor/Engineering,4,1.0,5.0,Single,Pre-Intermediate,7  8,...,1 - 2 hours,2,2,0,1,0,5,3,4,2
4,6,Female,21,Bachelor/Engineering,4,5.0,6.0,Single,Advanced,7  8,...,1 - 2 hours,3,5,5,1,0,5,6,4,5

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 825 entries, 0 to 824
Data columns (total 33 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  825 non-null    int64
 1   Gender              825 non-null    object
 2   Age                 825 non-null    int64
 3   EduLevel            825 non-null    object
 4   Year                825 non-null    int64
 5   MediaTime           825 non-null    float64
 6   FamChallenge        816 non-null    float64
 7   Relationship        825 non-null    object
 8   EngLevel            825 non-null    object
 9   SleepTime           825 non-null    object
 10  AcadStress          825 non-null    int64
 11  BacII               825 non-null    object
 12  Midterm             825 non-null    float64
 13  Final               825 non-null    float64
 14  Attendance          825 non-null    float64
 15  HWComplete          825 non-null    int64
 16  Clarify_Lecture     825 non-null    object
 17  IF_AIUse            822 non-null    object
 18  EngageListen        825 non-null    int64
 19  EngageAssignedWork  825 non-null    int64
 20  EngageAI            825 non-null    int64
 21  EngageGroup         825 non-null    int64
 22  Device4Learn        825 non-null    object
 23  MediaEntertain      825 non-null    object
 24  ClassMedia          825 non-null    int64
 25  ClassMessChat       825 non-null    int64
 26  ClassEntertain      825 non-null    int64
 27  ClassGames          825 non-null    int64
 28  ClassMovies         825 non-null    int64
 29  MindIntelligence    825 non-null    int64
 30  MindLearnMistake    825 non-null    int64
 31  MindSeekHelp        825 non-null    int64
 32  MindGroupWork       825 non-null    int64
dtypes: float64(5), int64(18), object(10)
memory usage: 212.8+ KB

# **2. DATA PREPROCESSING**
## **2.1 Handle Duplicated Value**
## **2.2 Handle Missing Value**

  ### **Fill Missing Value:**

*   IF_AIUse
*   FamChallenge


      
## **2.3 Feature Selection**
### **Drop Feature**
*   ID
### **Check Feature After Dropping**
### **Check Missing Value Again**

In [6]:
#Handle Duplicated
data.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
820    False
821    False
822    False
823    False
824    False
Length: 825, dtype: bool

In [7]:
#Handle Missing Value
data.isnull().sum()

ID                    0
Gender                0
Age                   0
EduLevel              0
Year                  0
MediaTime             0
FamChallenge          9
Relationship          0
EngLevel              0
SleepTime             0
AcadStress            0
BacII                 0
Midterm               0
Final                 0
Attendance            0
HWComplete            0
Clarify_Lecture       0
IF_AIUse              3
EngageListen          0
EngageAssignedWork    0
EngageAI              0
EngageGroup           0
Device4Learn          0
MediaEntertain        0
ClassMedia            0
ClassMessChat         0
ClassEntertain        0
ClassGames            0
ClassMovies           0
MindIntelligence      0
MindLearnMistake      0
MindSeekHelp          0
MindGroupWork         0
dtype: int64

In [8]:
data.isnull()

,ID,Gender,Age,EduLevel,Year,MediaTime,FamChallenge,Relationship,EngLevel,SleepTime,...,MediaEntertain,ClassMedia,ClassMessChat,ClassEntertain,ClassGames,ClassMovies,MindIntelligence,MindLearnMistake,MindSeekHelp,MindGroupWork
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
820,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
821,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
822,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
823,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
824,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [9]:
# make a copy Data first
df = data.copy()

In [10]:
# Check Missing Value
print(df.isnull().sum())

ID                    0
Gender                0
Age                   0
EduLevel              0
Year                  0
MediaTime             0
FamChallenge          9
Relationship          0
EngLevel              0
SleepTime             0
AcadStress            0
BacII                 0
Midterm               0
Final                 0
Attendance            0
HWComplete            0
Clarify_Lecture       0
IF_AIUse              3
EngageListen          0
EngageAssignedWork    0
EngageAI              0
EngageGroup           0
Device4Learn          0
MediaEntertain        0
ClassMedia            0
ClassMessChat         0
ClassEntertain        0
ClassGames            0
ClassMovies           0
MindIntelligence      0
MindLearnMistake      0
MindSeekHelp          0
MindGroupWork         0
dtype: int64

In [13]:
# fill numeric missing values with median
df["FamChallenge"] = df["FamChallenge"].fillna(df["FamChallenge"].median())

# fill categorical missing values with mode
df["IF_AIUse"] = df["IF_AIUse"].fillna(df["IF_AIUse"].mode()[0])

# check again
print(df.isnull().sum())

ID                    0
Gender                0
Age                   0
EduLevel              0
Year                  0
MediaTime             0
FamChallenge          0
Relationship          0
EngLevel              0
SleepTime             0
AcadStress            0
BacII                 0
Midterm               0
Final                 0
Attendance            0
HWComplete            0
Clarify_Lecture       0
IF_AIUse              0
EngageListen          0
EngageAssignedWork    0
EngageAI              0
EngageGroup           0
Device4Learn          0
MediaEntertain        0
ClassMedia            0
ClassMessChat         0
ClassEntertain        0
ClassGames            0
ClassMovies           0
MindIntelligence      0
MindLearnMistake      0
MindSeekHelp          0
MindGroupWork         0
dtype: int64

## **2.3 FEATURE SELECT**

In [14]:
# Drop Feature
df.drop('ID', axis=1, inplace=True)

In [15]:
#check Data Frame and Feature
df.head()

,Gender,Age,EduLevel,Year,MediaTime,FamChallenge,Relationship,EngLevel,SleepTime,AcadStress,...,MediaEntertain,ClassMedia,ClassMessChat,ClassEntertain,ClassGames,ClassMovies,MindIntelligence,MindLearnMistake,MindSeekHelp,MindGroupWork
0,Male,21,Bachelor/Engineering,4,4.0,6.0,Single,Advanced,5  6,7,...,More than 3 hours,4,4,4,0,0,5,5,5,5
1,Male,21,Bachelor/Engineering,4,7.0,2.0,Single,Advanced,7  8,4,...,More than 3 hours,3,3,3,1,1,6,6,6,6
2,Male,21,Bachelor/Engineering,4,8.0,3.0,Single,Advanced,5  6,7,...,More than 3 hours,4,3,3,0,4,6,6,5,4
3,Male,22,Bachelor/Engineering,4,1.0,5.0,Single,Pre-Intermediate,7  8,7,...,1 - 2 hours,2,2,0,1,0,5,3,4,2
4,Female,21,Bachelor/Engineering,4,5.0,6.0,Single,Advanced,7  8,4,...,1 - 2 hours,3,5,5,1,0,5,6,4,5

In [16]:
#Check Missing Value
df.isnull().sum()

Gender                0
Age                   0
EduLevel              0
Year                  0
MediaTime             0
FamChallenge          0
Relationship          0
EngLevel              0
SleepTime             0
AcadStress            0
BacII                 0
Midterm               0
Final                 0
Attendance            0
HWComplete            0
Clarify_Lecture       0
IF_AIUse              0
EngageListen          0
EngageAssignedWork    0
EngageAI              0
EngageGroup           0
Device4Learn          0
MediaEntertain        0
ClassMedia            0
ClassMessChat         0
ClassEntertain        0
ClassGames            0
ClassMovies           0
MindIntelligence      0
MindLearnMistake      0
MindSeekHelp          0
MindGroupWork         0
dtype: int64

In [17]:
for col in ["Midterm", "Final", "Attendance", "HWComplete"]:
    print(col, df[col].min(), df[col].max())

Midterm 30.0 100.0
Final 0.0 100.0
Attendance 30.0 100.0
HWComplete 0 100

In [18]:
# Check min Max of ["Midterm", "Final", "Attendance", "HWComplete"]
cols = ["Midterm", "Final", "Attendance", "HWComplete"]
print(df[cols].describe())
for col in cols:
    print(col, "min:", df[col].min(), "max:", df[col].max())

          Midterm       Final  Attendance  HWComplete
count  825.000000  825.000000  825.000000  825.000000
mean    63.087667   64.059967   89.075358   88.357576
std     14.343045   14.767319   13.085251   15.102944
min     30.000000    0.000000   30.000000    0.000000
25%     50.000000   50.000000   82.000000   80.000000
50%     60.000000   65.000000   93.000000   95.000000
75%     73.000000   75.000000  100.000000  100.000000
max    100.000000  100.000000  100.000000  100.000000
Midterm min: 30.0 max: 100.0
Final min: 0.0 max: 100.0
Attendance min: 30.0 max: 100.0
HWComplete min: 0 max: 100

In [19]:
# 1. Distribution of source variables
print(df[["Midterm", "Final", "Attendance", "HWComplete"]].describe())

          Midterm       Final  Attendance  HWComplete
count  825.000000  825.000000  825.000000  825.000000
mean    63.087667   64.059967   89.075358   88.357576
std     14.343045   14.767319   13.085251   15.102944
min     30.000000    0.000000   30.000000    0.000000
25%     50.000000   50.000000   82.000000   80.000000
50%     60.000000   65.000000   93.000000   95.000000
75%     73.000000   75.000000  100.000000  100.000000
max    100.000000  100.000000  100.000000  100.000000

In [24]:
# Create warning flags
df["MidtermWarning"] = (df["Midterm"] < 50).astype(int)
df["FinalWarning"] = (df["Final"] < 50).astype(int)
df["AttendanceWarning"] = (df["Attendance"] < 75).astype(int)
df["HWWarning"] = (df["HWComplete"] < 60).astype(int)

# Create risk score
df["RiskScore"] = (
    df["MidtermWarning"]
    + df["FinalWarning"]
    + df["AttendanceWarning"]
    + df["HWWarning"]
)

# Create final target variable
df["AcademicRisk"] = (df["RiskScore"] >= 2).astype(int)

# Check result
print(df[[
    "Midterm", "Final", "Attendance", "HWComplete",
    "MidtermWarning", "FinalWarning", "AttendanceWarning", "HWWarning",
    "RiskScore", "AcademicRisk"
]].head())

# Check class distribution
print(df["AcademicRisk"].value_counts())
print(df["AcademicRisk"].value_counts(normalize=True) * 100)

   Midterm  Final  Attendance  HWComplete  MidtermWarning  FinalWarning  \
0     85.0   80.0        95.0         100               0             0
1     86.0   88.0        80.0          90               0             0
2     82.0   82.0        85.0         100               0             0
3     84.0   87.0        80.0          90               0             0
4     70.0   75.0        80.0          80               0             0

   AttendanceWarning  HWWarning  RiskScore  AcademicRisk
0                  0          0          0             0
1                  0          0          0             0
2                  0          0          0             0
3                  0          0          0             0
4                  0          0          0             0
AcademicRisk
0    762
1     63
Name: count, dtype: int64
AcademicRisk
0    92.363636
1     7.636364
Name: proportion, dtype: float64

In [25]:
df.head()

,Gender,Age,EduLevel,Year,MediaTime,FamChallenge,Relationship,EngLevel,SleepTime,AcadStress,...,MindIntelligence,MindLearnMistake,MindSeekHelp,MindGroupWork,MidtermWarning,FinalWarning,AttendanceWarning,HWWarning,RiskScore,AcademicRisk
0,Male,21,Bachelor/Engineering,4,4.0,6.0,Single,Advanced,5  6,7,...,5,5,5,5,0,0,0,0,0,0
1,Male,21,Bachelor/Engineering,4,7.0,2.0,Single,Advanced,7  8,4,...,6,6,6,6,0,0,0,0,0,0
2,Male,21,Bachelor/Engineering,4,8.0,3.0,Single,Advanced,5  6,7,...,6,6,5,4,0,0,0,0,0,0
3,Male,22,Bachelor/Engineering,4,1.0,5.0,Single,Pre-Intermediate,7  8,7,...,5,3,4,2,0,0,0,0,0,0
4,Female,21,Bachelor/Engineering,4,5.0,6.0,Single,Advanced,7  8,4,...,5,6,4,5,0,0,0,0,0,0

In [26]:
df.isnull().sum()

Gender                0
Age                   0
EduLevel              0
Year                  0
MediaTime             0
FamChallenge          0
Relationship          0
EngLevel              0
SleepTime             0
AcadStress            0
BacII                 0
Midterm               0
Final                 0
Attendance            0
HWComplete            0
Clarify_Lecture       0
IF_AIUse              0
EngageListen          0
EngageAssignedWork    0
EngageAI              0
EngageGroup           0
Device4Learn          0
MediaEntertain        0
ClassMedia            0
ClassMessChat         0
ClassEntertain        0
ClassGames            0
ClassMovies           0
MindIntelligence      0
MindLearnMistake      0
MindSeekHelp          0
MindGroupWork         0
MidtermWarning        0
FinalWarning          0
AttendanceWarning     0
HWWarning             0
RiskScore             0
AcademicRisk          0
dtype: int64

In [27]:
print("Midterm < 50:", (df["Midterm"] < 50).sum())
print("Final < 50:", (df["Final"] < 50).sum())
print("Attendance < 75:", (df["Attendance"] < 75).sum())
print("HWComplete < 60:", (df["HWComplete"] < 60).sum())

Midterm < 50: 76
Final < 50: 63
Attendance < 75: 97
HWComplete < 60: 41